# Generated by Django 5.2.6 on 2025-09-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='adresse',
            field=models.CharField(default='Zac Mbao', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
