# Generated by Django 5.2.7 on 2025-10-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0006_classe_departement_bulletin_etudiant_classe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='emploidutemps',
            name='classe',
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('annee', models.PositiveIntegerField()),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFirstApp.filiere')),
            ],
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myFirstApp.promotion'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myFirstApp.promotion'),
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
    ]
