# Generated by Django 5.2.7 on 2025-10-21 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0007_remove_etudiant_classe_remove_emploidutemps_classe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='nom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='prenom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to=settings.AUTH_USER_MODEL),
        ),
    ]
